version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies" # Adds a "dependencies" label to the pull requests
    ignore:
      # only update on big new versions
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]